name: web_susch
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  slang: ^3.27.0
  slang_flutter: ^3.18.0
  # theme_tailor: ^2.0.0
  # theme_tailor_annotation: ^2.0.0
  go_router: ^10.0.0

  cupertino_icons: ^1.0.2
 
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  get_it: ^7.6.0

  chopper: ^7.0.5
  chopper_generator: ^7.0.2

  source_gen: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  email_validator: ^2.1.17
  flutter_native_splash: ^2.3.2
  logger: ^2.0.2
  get_storage: ^2.1.1

  scrollable_table_view: ^2.0.3
  json_annotation: ^4.8.1
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  file_picker: ^6.1.1
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^11.2.0
  dio: ^5.4.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.2

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:

    - assets/images/
